server:
    port: 8082

spring:
    application:
        name: Project-Portfolio
    datasource:
      url: jdbc:postgresql://localhost:5432/portfolio
      username: postgres
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
          client:
            requests: true

# JWT secret key (for demo only, store safely in real app!)
jwt:
  secret: nkWd3MDZVV449pLVJ7iIyfG+FhdKB4hK3N08IrIize4=  